// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/risk.proto

package risk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateRiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	ApplicantId   string                 `protobuf:"bytes,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	NominalAmount float64                `protobuf:"fixed64,3,opt,name=nominal_amount,json=nominalAmount,proto3" json:"nominal_amount,omitempty"`
	Organization  string                 `protobuf:"bytes,4,opt,name=organization,proto3" json:"organization,omitempty"`
	DocumentTypes []string               `protobuf:"bytes,5,rep,name=document_types,json=documentTypes,proto3" json:"document_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRiskRequest) Reset() {
	*x = CalculateRiskRequest{}
	mi := &file_proto_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRiskRequest) ProtoMessage() {}

func (x *CalculateRiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRiskRequest.ProtoReflect.Descriptor instead.
func (*CalculateRiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRiskRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *CalculateRiskRequest) GetApplicantId() string {
	if x != nil {
		return x.ApplicantId
	}
	return ""
}

func (x *CalculateRiskRequest) GetNominalAmount() float64 {
	if x != nil {
		return x.NominalAmount
	}
	return 0
}

func (x *CalculateRiskRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *CalculateRiskRequest) GetDocumentTypes() []string {
	if x != nil {
		return x.DocumentTypes
	}
	return nil
}

type CalculateRiskResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProposalId        string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	RiskLevel         string                 `protobuf:"bytes,2,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Confidence        float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	FeatureImportance map[string]float64     `protobuf:"bytes,4,rep,name=feature_importance,json=featureImportance,proto3" json:"feature_importance,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculateRiskResponse) Reset() {
	*x = CalculateRiskResponse{}
	mi := &file_proto_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRiskResponse) ProtoMessage() {}

func (x *CalculateRiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRiskResponse.ProtoReflect.Descriptor instead.
func (*CalculateRiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateRiskResponse) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *CalculateRiskResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *CalculateRiskResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CalculateRiskResponse) GetFeatureImportance() map[string]float64 {
	if x != nil {
		return x.FeatureImportance
	}
	return nil
}

var File_proto_risk_proto protoreflect.FileDescriptor

const file_proto_risk_proto_rawDesc = "" +
	"\n" +
	"\x10proto/risk.proto\x12\x04risk\"\xcc\x01\n" +
	"\x14CalculateRiskRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12!\n" +
	"\fapplicant_id\x18\x02 \x01(\tR\vapplicantId\x12%\n" +
	"\x0enominal_amount\x18\x03 \x01(\x01R\rnominalAmount\x12\"\n" +
	"\forganization\x18\x04 \x01(\tR\forganization\x12%\n" +
	"\x0edocument_types\x18\x05 \x03(\tR\rdocumentTypes\"\xa0\x02\n" +
	"\x15CalculateRiskResponse\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\tR\triskLevel\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12a\n" +
	"\x12feature_importance\x18\x04 \x03(\v22.risk.CalculateRiskResponse.FeatureImportanceEntryR\x11featureImportance\x1aD\n" +
	"\x16FeatureImportanceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012W\n" +
	"\vRiskService\x12H\n" +
	"\rCalculateRisk\x12\x1a.risk.CalculateRiskRequest\x1a\x1b.risk.CalculateRiskResponseB)Z'github.com/rizky/smart-grant/proto/riskb\x06proto3"

var (
	file_proto_risk_proto_rawDescOnce sync.Once
	file_proto_risk_proto_rawDescData []byte
)

func file_proto_risk_proto_rawDescGZIP() []byte {
	file_proto_risk_proto_rawDescOnce.Do(func() {
		file_proto_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_risk_proto_rawDesc), len(file_proto_risk_proto_rawDesc)))
	})
	return file_proto_risk_proto_rawDescData
}

var file_proto_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_risk_proto_goTypes = []any{
	(*CalculateRiskRequest)(nil),  // 0: risk.CalculateRiskRequest
	(*CalculateRiskResponse)(nil), // 1: risk.CalculateRiskResponse
	nil,                           // 2: risk.CalculateRiskResponse.FeatureImportanceEntry
}
var file_proto_risk_proto_depIdxs = []int32{
	2, // 0: risk.CalculateRiskResponse.feature_importance:type_name -> risk.CalculateRiskResponse.FeatureImportanceEntry
	0, // 1: risk.RiskService.CalculateRisk:input_type -> risk.CalculateRiskRequest
	1, // 2: risk.RiskService.CalculateRisk:output_type -> risk.CalculateRiskResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_risk_proto_init() }
func file_proto_risk_proto_init() {
	if File_proto_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_risk_proto_rawDesc), len(file_proto_risk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_risk_proto_goTypes,
		DependencyIndexes: file_proto_risk_proto_depIdxs,
		MessageInfos:      file_proto_risk_proto_msgTypes,
	}.Build()
	File_proto_risk_proto = out.File
	file_proto_risk_proto_goTypes = nil
	file_proto_risk_proto_depIdxs = nil
}
